### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by rasadeghnasab** [SUKOHI/Maven#1]
It think it is a problem with this line of documentation:
`$faqs = \Maven::tag(['YOUR-TAG-1', 'YOUR-TAG-2'])->get();`
I gone throw package codes and found that this is the write way to get faqs base on tags:
`$faqs = \Maven::tag(['en' => 'YOUR-TAG-1', 'YOUR-TAG-2'], 'otherLang' => ['TAG3', 'Tag4'])->get();`

**Comment by SUKOHI** [comment]
Hi, Raminsadeghi.
Thank you for your message.
You are ablosutely right!

And I changed the README.md as you indicated.
And I included your name with GitHub URL in appreciate for it.
(If you mind, please inform me of it.)

Thank you  again. :)))
